version: '3'

vars:
  DEV_COMPOSE_FILE: docker/development/docker-compose.dev.yml
  PROD_COMPOSE_FILE: docker/production/docker-compose.prod.yml
  container_name: workspace


tasks:
  dev-reset-all:
    desc: Rebuild and restart development environment
    cmds:
      - docker compose -f {{.DEV_COMPOSE_FILE}} down -v
      - docker compose -f {{.DEV_COMPOSE_FILE}} build --no-cache
      - docker compose -f {{.DEV_COMPOSE_FILE}} up

  dev-down-up:
    desc: down and restart development environment
    cmds:
      - docker compose -f {{.DEV_COMPOSE_FILE}} down
      - docker compose -f {{.DEV_COMPOSE_FILE}} up

  prod-reset-all:
    desc: Rebuild and restart development environment
    cmds:
      - docker compose -f {{.PROD_COMPOSE_FILE}} down -v
      - docker compose -f {{.PROD_COMPOSE_FILE}} build --no-cache
      - docker compose -f {{.PROD_COMPOSE_FILE}} up

  dev-cmd:
    desc: Run a command in the development environment
    cmds:
      - docker compose -f {{.DEV_COMPOSE_FILE}} exec {{.container_name}} {{.CLI_ARGS}}

