FROM node:18-alpine AS base

RUN npm install -g pnpm

WORKDIR /app

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./

COPY api/package.json ./api/
COPY web/package.json ./web/

RUN pnpm install --frozen-lockfile