
services:
  # 基础镜像
  base:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile.base
    image: next-nest-app-base:latest

  # API 服务
  api:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile.api
    depends_on:
      - base
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  # Web 服务
  web:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile.web
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    depends_on:
      - base
      - api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  # Nginx 反向代理（可选但推荐）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web
